# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(578, 548)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 561, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.cmValue = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.cmValue.setObjectName("cmValue")
        self.gridLayout.addWidget(self.cmValue, 0, 0, 1, 1)
        self.calValue = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.calValue.setObjectName("calValue")
        self.gridLayout.addWidget(self.calValue, 0, 2, 1, 1)
        self.mValue = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.mValue.setObjectName("mValue")
        self.gridLayout.addWidget(self.mValue, 1, 0, 1, 1)
        self.kmValue = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.kmValue.setObjectName("kmValue")
        self.gridLayout.addWidget(self.kmValue, 2, 0, 1, 1)
        self.sValue = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.sValue.setObjectName("sValue")
        self.gridLayout.addWidget(self.sValue, 1, 2, 1, 1)
        self.milValue = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.milValue.setObjectName("milValue")
        self.gridLayout.addWidget(self.milValue, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "cm/cal"))
        self.label_2.setText(_translate("Dialog", "m/stopy"))
        self.label_3.setText(_translate("Dialog", "km/mile"))
